### PR TITLE
issue-222 adding elasticsearch ssl support

### PR DESCRIPTION
**Pull request by KurtStam**

### CODE REVIEW

**Comment by jimmidyson** [comment]
Can you squash commits please?

**Comment by jimmidyson** [comment]
Oh OK auto-merged without squashing... not the best idea IMO.

**Comment by KurtStam** [comment]
Y had to board.. Poor judgement on my part

On May 12, 2016, at 17:13, Jimmi Dyson <notifications@github.com> wrote:

Oh OK auto-merged without squashing... not the best idea IMO.

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/fabric8io/fabric8-ipaas/pull/309#issuecomment-218807368>

**Comment by jimmidyson** [comment]
Planes wait for no man.

**Pull request merged**
