### PR TITLE
Upgrading apiman to 1.2.3.Final, #170, #178

### PR DESCRIPTION
**Pull request by KurtStam**

### CODE REVIEW

**Comment by KurtStam** [comment]
retest please

**Comment by rawlingsj** [comment]
@KurtStam can you try the retest command again.  I've just added you to the admin list in jenkins - lets see if it works.

**Comment by KurtStam** [comment]
retest please

**Comment by KurtStam** [comment]
yay!

**Comment by rawlingsj** [comment]
there you go :)

**Pull request merged**
