### PR TITLE
Fix for #338 

### PR DESCRIPTION
**Pull request by rajdavies**
Swapped out nats client library - which seems to be the issue with https://github.com/fabric8io/fabric8-ipaas/issues/338

### CODE REVIEW

**Comment by rawlingsj** [comment]
[merge]

**Comment by rawlingsj** [comment]
CI needs that fancy merge comment these days

**Comment by jimmidyson** [comment]
@rawlingsj Previously any comment on a PR would have caused it to be merged. That meant you couldn't review any changes& give feedback without it being merged... not a great idea really.

**Comment by rawlingsj** [comment]
@jimmidyson where's this configuration and is it sorted for all projects now?  The merge comment approach was taken from the kubernetes-client pull request job so I'm wondering if the any comment thing is default configuration - it's not supposed to be like that.  If you can let me know where the config is I'll check all the PR jobs.

**Comment by jimmidyson** [comment]
@rawlingsj I think I've gone through all PR jobs & done it already. Pretty sure it was never part of the base kubernetes client PR job but will double check now.

**Pull request merged**
